/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NgoManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.NgoEnterprise;
import Business.Network.Network;
import Business.Organization.NgoManagerOrganization;

import Business.Organization.Organization;
import Business.Organization.ResourceCollectorOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkAddResourse;
import Business.WorkQueue.WorkAidRequest;
import Business.WorkQueue.WorkRegistration;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.googlemap.googlemappanel;
import Business.googlemap.map;

/**
 *
 * @author hp
 */
public class NgoManagerWorkAreaPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private NgoManagerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem ecosystem;
    private Network network;
    private int food=0;
    private map Map;
    /**
     * Creates new form NgoManagerWorkAreaPanel
     */
    public NgoManagerWorkAreaPanel(JPanel userProcessContainer, UserAccount account, NgoManagerOrganization organization, Enterprise enterprise,EcoSystem business,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.ecosystem=business;
        this.network=network;
       
        this.calculatefood();
         this.amount_label.setText(String.valueOf(this.food));
        this.populatetablereceive();
        this.populatetablesend();
       
    }

    
    
   
    
    public void calculatefood()
    {
       for ( Organization org :this.enterprise.getOrganizationDirectory().getOrganizationList())
       {
           if (org instanceof ResourceCollectorOrganization){
               
               for(WorkAddResourse war: org.getWorkQueue().getAddresourceList())
               {
                   if(war.getSign()==1)
                   this.food+=war.getNumber();
                   else
                       this.food-=war.getNumber();
               }
           }
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button_accept = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        amount_label = new javax.swing.JLabel();
        Button_sendin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_receive = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_send = new javax.swing.JTable();
        Button_decline1 = new javax.swing.JButton();
        Button_receive = new javax.swing.JButton();
        Button_sendout = new javax.swing.JButton();
        text_help = new javax.swing.JTextField();
        error_no = new javax.swing.JLabel();
        Button_map = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextField_address = new javax.swing.JTextField();
        error_no1 = new javax.swing.JLabel();
        error_add = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        Button_accept.setBackground(new java.awt.Color(51, 153, 255));
        Button_accept.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_accept.setText("Accept");
        Button_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_acceptActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel1.setText("Resources Available  :");

        amount_label.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N

        Button_sendin.setBackground(new java.awt.Color(51, 153, 255));
        Button_sendin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_sendin.setText("Request Other Ngo >>");
        Button_sendin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_sendinActionPerformed(evt);
            }
        });

        jTable_receive.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sno", "Person", "Status", "request sender"
            }
        ));
        jScrollPane1.setViewportView(jTable_receive);

        jTable_send.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sno", "person", "status", "Ngoreceiver"
            }
        ));
        jScrollPane2.setViewportView(jTable_send);

        Button_decline1.setBackground(new java.awt.Color(51, 153, 255));
        Button_decline1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_decline1.setText("Decline");
        Button_decline1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_decline1ActionPerformed(evt);
            }
        });

        Button_receive.setBackground(new java.awt.Color(51, 153, 255));
        Button_receive.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_receive.setText("Receive");
        Button_receive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_receiveActionPerformed(evt);
            }
        });

        Button_sendout.setBackground(new java.awt.Color(51, 153, 255));
        Button_sendout.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_sendout.setText("Request Other Countries Ngo >>");
        Button_sendout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_sendoutActionPerformed(evt);
            }
        });

        text_help.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        error_no.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        error_no.setForeground(new java.awt.Color(255, 0, 0));

        Button_map.setBackground(new java.awt.Color(51, 153, 255));
        Button_map.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_map.setText("See Map");
        Button_map.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_mapActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel2.setText("Help For People  :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel3.setText("Address:");

        TextField_address.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TextField_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_addressActionPerformed(evt);
            }
        });

        error_no1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        error_no1.setForeground(new java.awt.Color(255, 51, 51));

        error_add.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        error_add.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Button_sendin, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(error_no, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                        .addGap(293, 293, 293)
                        .addComponent(Button_sendout, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Button_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(Button_decline1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(Button_receive, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_map, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(amount_label, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_help, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(TextField_address))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(error_add, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(error_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 278, Short.MAX_VALUE)))
                .addContainerGap(536, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(amount_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_decline1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_receive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_map, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(error_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(text_help, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(error_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextField_address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(error_no, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_sendin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_sendout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(83, 83, 83))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel4.setText("Welcome To Ngo Manager Work Area ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(jLabel4)
                .addContainerGap(760, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void populatetablereceive()
    {
         DefaultTableModel model = (DefaultTableModel) this.jTable_receive.getModel();
        
        model.setRowCount(0);
        int x=0;
        
                    for (WorkAidRequest war : this.organization.getWorkQueue().getAidrequestList()){
                        if(war.getNgoreciever()==this.userAccount || war.getNgoreciever()==null && war.getRequestsender()!=this.userAccount)
                        {
                         Object[] row = new Object[4]; x++;
                         row[0] = x;
                         row[1] = war.getAmount();
                         row[2] = war;
                         row[3] = war.getRequestsender();
                        
                         model.addRow(row);
                         }
                    }
       
    }
    
    public void populatetablesend()
    {
         DefaultTableModel model = (DefaultTableModel) this.jTable_send.getModel();
        
        model.setRowCount(0);
        int x=0;
        
                    for (WorkAidRequest war : this.organization.getWorkQueue().getAidrequestList()){
                        if(war.getRequestsender()==this.userAccount)
                        {
                         Object[] row = new Object[4]; x++;
                         row[0] = x;
                         row[1] = war.getAmount();
                         row[2] = war;
                         row[3] = war.getNgoreciever();
                        
                         model.addRow(row);
                         }
                    }
       
    }
    public boolean validatef(){
        
        boolean bno=true , badd=true;
        String regex="\\d+";
        
                try
                {
                    error_no.setText("");
                Integer.parseInt(this.text_help.getText());
                }
                catch(NumberFormatException e)
                {
                if(text_help.getText().isEmpty()) this.error_no.setText("can not be empty");   
                else
                error_no.setText("enter valid number");
                bno=false;
                }
        
   
        
        if(this.TextField_address.getText().isEmpty())
        {
            this.error_add.setText("Plz Enter Text"); badd=false;
        }
        else if(TextField_address.getText().matches(regex))
                {
                    error_add.setText("can't be a number"); badd=false;
                }
        else this.error_add.setText("");
        
        if(!badd || !bno) return false;
        return true;
    }
    private void Button_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_acceptActionPerformed
        // TODO add your handling code here:
       
        int sr = this.jTable_receive.getSelectedRow();
        if(sr>=0)
        {
            WorkAidRequest  war =  (WorkAidRequest) jTable_receive.getValueAt(sr, 2);
            
            if(war.getNgoreciever()==null)
            {
            JOptionPane.showMessageDialog(null,"Please Recieve First"); return;
            }
            
            if(war.getStatus().equals("approved"))
             {JOptionPane.showMessageDialog(null,"already approved"); return; }
            if(war.getStatus().equals("declined"))
             {JOptionPane.showMessageDialog(null,"already declined"); return; }
            
            int x= Integer.parseInt(jTable_receive.getValueAt(sr, 1).toString());
            if(x>this.food-10)
                {JOptionPane.showMessageDialog(null,"Less resourse available"); return;}
             
             war.setStatus("approved");
             
             this.food=0;
        WorkAddResourse warr = new WorkAddResourse();
        warr.setNumber(x);
        warr.setSign(0);
        warr.setUser(userAccount);
        for ( Organization org :this.enterprise.getOrganizationDirectory().getOrganizationList())
       {
           if (org instanceof ResourceCollectorOrganization){
               
               org.getWorkQueue().getAddresourceList().add(warr);
           }
       }
        
       if(war.getEnterprise()!=null)
       {
        WorkAddResourse warr1 = new WorkAddResourse();
        warr1.setNumber(x);
        warr1.setSign(1);
        warr1.setUser(userAccount);
           
           for ( Organization org :war.getEnterprise().getOrganizationDirectory().getOrganizationList())
       {
           if (org instanceof ResourceCollectorOrganization){
               
               org.getWorkQueue().getAddresourceList().add(warr1);
           }
       }
       }
        
        
        this.calculatefood();
        this.amount_label.setText(String.valueOf(this.food));
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Select a specific detail ");
        }
        
        
        this.populatetablereceive();
        
    }//GEN-LAST:event_Button_acceptActionPerformed

    private void Button_sendinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_sendinActionPerformed
               // TODO add your handling code here:
                 
                if(this.validatef()==false)return;
        
                Organization org = null;
                Enterprise epp=null;
                WorkAidRequest war = new WorkAidRequest();
                war.setAmount(Integer.parseInt(text_help.getText()));
                war.setRequestsender(userAccount);
                war.setStatus("sent to Ngos");
                war.setEnterprise(enterprise);
                war.setAddress(this.TextField_address.getText());
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())
                {
                if (enterprise instanceof NgoEnterprise   )
                   {
                       epp=enterprise;
                       System.out.println(enterprise);
                       for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
                       {
                       if (organization instanceof NgoManagerOrganization)
                          {
                              
                              System.out.println(organization);
                              org = organization;
                              org.getWorkQueue().getAidrequestList().add(war);
                
                          }   
                       }
                
                
                   }   
                }
                if(epp==null)
                   {JOptionPane.showMessageDialog(null,"There is no Ngo Enterprise"); return;}
                
                if(org==null)
                   {JOptionPane.showMessageDialog(null,"There is no ngomanager Organization"); return;}
               
                //organization.getWorkQueue().getAidrequestList().add(war);
               
                JOptionPane.showMessageDialog(null,"Request sent"); 
               
               
               
                this.populatetablesend();
                this.populatetablereceive();
                this.TextField_address.setText("");
                this.text_help.setText("");
        
        
    }//GEN-LAST:event_Button_sendinActionPerformed

    private void Button_decline1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_decline1ActionPerformed
        // TODO add your handling code here:
        
        int sr = this.jTable_receive.getSelectedRow();
        if(sr>=0)
        {
            WorkAidRequest  war =  (WorkAidRequest) jTable_receive.getValueAt(sr, 2);
            
            
            if(war.getNgoreciever()==null)
            {
            JOptionPane.showMessageDialog(null,"Please Recieve First"); return;
            }
           
             if(war.getStatus().equals("approved"))
             {JOptionPane.showMessageDialog(null,"already approved"); return; }
             if(war.getStatus().equals("declined"))
             {JOptionPane.showMessageDialog(null,"already declined"); return; }
             war.setStatus("declined");
             
             
             
             
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Select a specific detail ");
        }
        
        
        this.populatetablereceive();
        
    }//GEN-LAST:event_Button_decline1ActionPerformed

    private void Button_receiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_receiveActionPerformed
        // TODO add your handling code here:
        
        int sr = this.jTable_receive.getSelectedRow();
        if(sr>=0)
        {
            
            WorkAidRequest  war =  (WorkAidRequest) jTable_receive.getValueAt(sr, 2);
            if(!war.getStatus().equals("sent to Ngos")){ JOptionPane.showMessageDialog(null,"Already Received"); return;}
            war.setStatus("Received at ngo");
            war.setNgoreciever(userAccount);
            this.populatetablereceive();
            JOptionPane.showMessageDialog(null,"Request received");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Select a specific detail ");
        }
    }//GEN-LAST:event_Button_receiveActionPerformed

    private void Button_sendoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_sendoutActionPerformed
        // TODO add your handling code here:
        if(this.validatef()==false)return;
        Organization org = null;
         Enterprise epp=null;
                WorkAidRequest war = new WorkAidRequest();
                war.setAmount(Integer.parseInt(this.text_help.getText()));
                war.setRequestsender(userAccount);
                war.setStatus("sent to Ngos");
                war.setEnterprise(this.enterprise);
                war.setAddress(this.TextField_address.getText());
                
                for (Network network : this.ecosystem.getNetworkList())
                {
                    for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())
                {
                if (enterprise instanceof NgoEnterprise  )
                   {
                       epp=enterprise;
                       System.out.println(enterprise);
                       for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
                       {
                       if (organization instanceof NgoManagerOrganization)
                          {
                              
                              System.out.println(organization);
                              org = organization;
                              org.getWorkQueue().getAidrequestList().add(war);
                
                          }   
                       }
                
                
                   }   
                }
                }
                
                
                if(epp==null)
                   {JOptionPane.showMessageDialog(null,"There is no Ngo Enterprise"); return;}
                
               if(org==null)
                   {JOptionPane.showMessageDialog(null,"There is no ngomanager Organization"); return;}
               
               //this.organization.getWorkQueue().getAidrequestList().add(war);
               
               JOptionPane.showMessageDialog(null,"Request sent"); 
               this.populatetablesend();
       this.TextField_address.setText("");
       this.text_help.setText("");
        
    }//GEN-LAST:event_Button_sendoutActionPerformed

    private void Button_mapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_mapActionPerformed
        // TODO add your handling code here:
        
        int sr = this.jTable_receive.getSelectedRow();
        if(sr>=0)
        {
            
            WorkAidRequest  war =  (WorkAidRequest) jTable_receive.getValueAt(sr, 2);
        
            googlemappanel googlePanel = new googlemappanel(Map,war.getAddress());
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Select a specific detail ");
        }
        
    }//GEN-LAST:event_Button_mapActionPerformed

    private void TextField_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_addressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_accept;
    private javax.swing.JButton Button_decline1;
    private javax.swing.JButton Button_map;
    private javax.swing.JButton Button_receive;
    private javax.swing.JButton Button_sendin;
    private javax.swing.JButton Button_sendout;
    private javax.swing.JTextField TextField_address;
    private javax.swing.JLabel amount_label;
    private javax.swing.JLabel error_add;
    private javax.swing.JLabel error_no;
    private javax.swing.JLabel error_no1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_receive;
    private javax.swing.JTable jTable_send;
    private javax.swing.JTextField text_help;
    // End of variables declaration//GEN-END:variables
}
