/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManagerRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.EmbassyEnterprise;
import Business.Organization.ApprovalOrganization;
import Business.Organization.ManagerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRegistration;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import Business.Network.Network;
import Chart.Charts;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import userinterface.RegisterationRole.NewRegisterJPanel;

/**
 *
 * @author hp
 */
public class ManagerWorkAreaPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private ManagerOrganization organization;
    private Enterprise enterprise;
    private Network network;
    private UserAccount userAccount;
    
    /**
     * Creates new form ManagerWorkAreaPanel
     */
    public ManagerWorkAreaPanel(JPanel userProcessContainer, UserAccount account, ManagerOrganization organization, Enterprise enterprise ,Network network ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network=network;
        //valueLabel.setText(enterprise.getName());
        populateRequestTable();
        
       
    }

    
    public void populateRequestTable(){
        
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        
        model.setRowCount(0);
        int x=0;
        
                    for (WorkRegistration register : this.organization.getWorkQueue().getRegistrationList()){
                        if(register.getUnosender()==null || register.getUnosender()==this.userAccount)
                        {
                         Object[] row = new Object[4]; x++;
                         row[0] = x;
                         row[1]= register;
                         row[2] =register.getCountry();
                         row[3] = register.getStatus();
                         
                         
                         model.addRow(row);
                         }
                    }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Send = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Button_Assignme = new javax.swing.JButton();
        Button_seedetail = new javax.swing.JButton();
        Button_analysis = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        Send.setBackground(new java.awt.Color(51, 153, 255));
        Send.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Send.setText("Send >>");
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sno", "RefugeeId", "Migrationcountry", "status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Button_Assignme.setBackground(new java.awt.Color(51, 153, 255));
        Button_Assignme.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_Assignme.setText("Assign To Me ");
        Button_Assignme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AssignmeActionPerformed(evt);
            }
        });

        Button_seedetail.setBackground(new java.awt.Color(51, 153, 255));
        Button_seedetail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_seedetail.setText("See  Details");
        Button_seedetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_seedetailActionPerformed(evt);
            }
        });

        Button_analysis.setBackground(new java.awt.Color(51, 153, 255));
        Button_analysis.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_analysis.setText("See Analysis");
        Button_analysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_analysisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Button_Assignme)
                        .addGap(102, 102, 102)
                        .addComponent(Button_seedetail)
                        .addGap(123, 123, 123)
                        .addComponent(Button_analysis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Send, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button_Assignme)
                        .addComponent(Button_seedetail)
                        .addComponent(Button_analysis))
                    .addComponent(Send))
                .addGap(251, 251, 251))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel4.setText("Welcome To Manager Work Area ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        // TODO add your handling code here:
        
        int sr = jTable1.getSelectedRow();
        if(sr>=0)
        {
            
             WorkRegistration  wr =  (WorkRegistration) jTable1.getValueAt(sr, 1);
             
             if(wr.getUnosender()==null)
             {
                 JOptionPane.showMessageDialog(null,"job Didnt assigned yet"); return;
             }
             if(!wr.getStatus().equals("Manager Received")){ JOptionPane.showMessageDialog(null,"Already Sent"); return;}
             Organization org = null;
             Enterprise epp=null;
             for (Enterprise enterprise : this.network.getEnterpriseDirectory().getEnterpriseList()){
             if (enterprise instanceof EmbassyEnterprise){
                 if(enterprise.getName().equalsIgnoreCase(wr.getCountry()))
                 {
                     epp = enterprise;
                     break;
                 }
                 
               }
              }
             //epp=(Enterprise)this.Combo_enterprise.getSelectedItem();
             if (epp!=null){
             for (Organization organization : epp.getOrganizationDirectory().getOrganizationList()){
             if (organization instanceof ApprovalOrganization){
                org = organization;
                break;
               }
              }
             }else {JOptionPane.showMessageDialog(null,"There is no Embassy"); return;}
             
            if (org!=null){
            org.getWorkQueue().getRegistrationList().add(wr);
            userAccount.getWorkQueue().getRegistrationList().add(wr);
            wr.setStatus("sent to ebmassy");
            
            JOptionPane.showMessageDialog(null,"details sent ");
            }
            else
            {
            JOptionPane.showMessageDialog(null,"There is no ApprovalOrganization");
            } 
            this.populateRequestTable();
        }else
        {
            JOptionPane.showMessageDialog(null,"Please Select a specific detail ");
        }
        
        
        
        
    }//GEN-LAST:event_SendActionPerformed

    private void Button_AssignmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AssignmeActionPerformed
        // TODO add your handling code here:
        
        
        int sr = jTable1.getSelectedRow();
        if(sr>=0)
        {
            WorkRegistration  wr =  (WorkRegistration) jTable1.getValueAt(sr, 1);
            if(wr.getStatus()!=null){ JOptionPane.showMessageDialog(null,"Already Recieved"); return;}
            wr.setStatus("Manager Received");
            wr.setUnosender(this.userAccount);
            this.populateRequestTable();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Select a specific detail ");
        }
    }//GEN-LAST:event_Button_AssignmeActionPerformed

    private void Button_seedetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_seedetailActionPerformed
        // TODO add your handling code here:
        
         int sr = jTable1.getSelectedRow();
        if(sr>=0)
        {
            WorkRegistration  wr =  (WorkRegistration) jTable1.getValueAt(sr, 1);
            RefugeeDetailPanel refufeedetail = new RefugeeDetailPanel(userProcessContainer, userAccount, enterprise, network, wr);
            userProcessContainer.add("refufeedetail", refufeedetail);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Select a specific detail ");
        }
        
        
    }//GEN-LAST:event_Button_seedetailActionPerformed

    private void Button_analysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_analysisActionPerformed
        // TODO add your handling code here:
        HashMap<String, Integer> temp = new LinkedHashMap<String, Integer>();
        HashMap<String, Integer> a2 = new LinkedHashMap<String, Integer>();
        HashMap<String, Integer> per = new LinkedHashMap<String, Integer>();
        for (WorkRegistration register : this.organization.getWorkQueue().getRegistrationList())
        {
            int i =1;
            if(temp.containsKey(register.getCountry()))
            {
                i=temp.get(register.getCountry()); i++;
            }
            temp.put(register.getCountry(), i);
        }
        
        for (WorkRegistration register : this.organization.getWorkQueue().getRegistrationList())
        {
            int i =0;
            if(a2.containsKey(register.getCountry()))
            {
                if(register.getStatus()!=null)
                {
                    if(register.getStatus().equals("approved"))
                    {
                    i=a2.get(register.getCountry()); 
                    i++;}
                }
            }
            else if(register.getStatus()!=null)
                {
                    if(register.getStatus().equals("approved"))
                    {
                    a2.put(register.getCountry(), 1);
                    }
                }
            
        }
        for (Map.Entry<String, Integer> entrySet : a2.entrySet())
        {
            int i=temp.get(entrySet.getKey());
            if(i==0)
            per.put(entrySet.getKey(),0 );
            else
            {
                int x=entrySet.getValue()*100/i;
      
                 per.put(entrySet.getKey(), x );
            }
               
        }
        
        Charts build = new Charts("Analysis", "Number of Applications To Countries", temp);
        build.pack();
        build.setVisible(true);
        Charts build1 = new Charts("Analysis", "Approved Percentage From Countries", per);
        build1.pack();
        build1.setVisible(true);
        
    }//GEN-LAST:event_Button_analysisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Assignme;
    private javax.swing.JButton Button_analysis;
    private javax.swing.JButton Button_seedetail;
    private javax.swing.JButton Send;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
