/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRegistration;
import Business.WorkQueue.refugeedetails;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import Business.pdf.pdfgenerate;

/**
 *
 * @author hp
 */
public class RefugeeDetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form Refugee_details
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem ecosystem;
    private Network network;
    private WorkRegistration wr;
    private refugeedetails rd;
    public RefugeeDetailPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network,WorkRegistration wr) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.ecosystem=ecosystem;
        this.network=network;
        this.wr=wr;
        this.deserialize();
        this.setfields();
        this.fieldsdisable();
    }
    
    public void fieldsdisable()
    {
        this.txt_child.setEditable(false);
        this.Text_Age.setEditable(false);
        this.Text_Name.setEditable(false);
        this.Text_country.setEditable(false);
        this.Text_gender.setEditable(false);
        this.txt_fathernam.setEditable(false);
        this.txt_mothername.setEditable(false);
    }
    public void deserialize()
    {
        
      try {
         FileInputStream fileIn = new FileInputStream("Rfiles/"+this.wr.getFilename());
         ObjectInputStream in = new ObjectInputStream(fileIn);
         this.rd = (refugeedetails) in.readObject();
         in.close();
         fileIn.close();
      } catch (IOException i) {
         i.printStackTrace();
         return;
      } catch (ClassNotFoundException c) {
         System.out.println("refugee class not found");
         c.printStackTrace();
         return;
      }
    }
    
     public ImageIcon ResizeImage(String Imagepath)
    {
        ImageIcon Myimage = new ImageIcon(Imagepath);
        Image img = Myimage.getImage();
        Image newimg = img.getScaledInstance(249, 258,Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newimg);
        return image;
    }
     
    public void setfields()
    {
        
        this.Text_Age.setText(String.valueOf(this.rd.getAge()));
        this.Text_Name.setText(this.rd.getName());
        this.Text_country.setText(this.rd.getCountry());
        this.Text_gender.setText(this.rd.getGender());
        this.txt_fathernam.setText(this.rd.getFathername());
        this.txt_mothername.setText(this.rd.getMothername());
        this.txt_child.setText(String.valueOf(this.rd.getChildno()));
        
        this.label_image.setIcon(ResizeImage( new File("Image\\"+wr.getImage_path()).getAbsolutePath()));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button_Back = new javax.swing.JButton();
        Label_country = new javax.swing.JLabel();
        Label_Gender = new javax.swing.JLabel();
        Labe_Age = new javax.swing.JLabel();
        Text_Age = new javax.swing.JTextField();
        Label_name = new javax.swing.JLabel();
        Text_Name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_fathernam = new javax.swing.JTextField();
        txt_mothername = new javax.swing.JTextField();
        txt_child = new javax.swing.JTextField();
        Text_country = new javax.swing.JTextField();
        Text_gender = new javax.swing.JTextField();
        label_image = new javax.swing.JLabel();
        Button_Back1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        Button_Back.setBackground(new java.awt.Color(51, 153, 255));
        Button_Back.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_Back.setText("<<  Back");
        Button_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BackActionPerformed(evt);
            }
        });

        Label_country.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_country.setText("Country");

        Label_Gender.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_Gender.setText("Gender");

        Labe_Age.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Labe_Age.setText("Age");

        Text_Age.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Text_Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_AgeActionPerformed(evt);
            }
        });

        Label_name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Label_name.setText("Name");

        Text_Name.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Text_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_NameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("DETAILS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Father's Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Mother's Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("No of Child");

        txt_fathernam.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_fathernam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fathernamActionPerformed(evt);
            }
        });

        txt_mothername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txt_child.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        Text_country.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Text_country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_countryActionPerformed(evt);
            }
        });

        Text_gender.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Text_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_genderActionPerformed(evt);
            }
        });

        label_image.setText("jLabel6");

        Button_Back1.setBackground(new java.awt.Color(51, 153, 255));
        Button_Back1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_Back1.setText("Generate Pdf");
        Button_Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Back1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Button_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(Button_Back1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Labe_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_name, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(Label_country, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_child)
                                .addComponent(txt_mothername, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Text_country, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                .addComponent(txt_fathernam, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Text_Age, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                .addComponent(Text_Name)
                                .addComponent(Text_gender)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 410, Short.MAX_VALUE)
                .addComponent(label_image, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(297, 297, 297))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_name)
                            .addComponent(Text_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Labe_Age)
                            .addComponent(Text_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Gender)
                            .addComponent(Text_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Label_country)
                            .addComponent(Text_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label_image, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fathernam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mothername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_child, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Back)
                    .addComponent(Button_Back1))
                .addGap(154, 154, 154))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel4.setText("Welcome To New Registarion Work Area ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(jLabel4)
                .addContainerGap(645, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_Button_BackActionPerformed

    private void Text_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_NameActionPerformed

    private void Text_countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_countryActionPerformed

    private void Text_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_genderActionPerformed

    private void txt_fathernamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fathernamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fathernamActionPerformed

    private void Text_AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_AgeActionPerformed

    private void Button_Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Back1ActionPerformed
        // TODO add your handling code here:
        pdfgenerate pg = new pdfgenerate(this.wr);
        
        
    }//GEN-LAST:event_Button_Back1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Back;
    private javax.swing.JButton Button_Back1;
    private javax.swing.JLabel Labe_Age;
    private javax.swing.JLabel Label_Gender;
    private javax.swing.JLabel Label_country;
    private javax.swing.JLabel Label_name;
    private javax.swing.JTextField Text_Age;
    private javax.swing.JTextField Text_Name;
    private javax.swing.JTextField Text_country;
    private javax.swing.JTextField Text_gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label_image;
    private javax.swing.JTextField txt_child;
    private javax.swing.JTextField txt_fathernam;
    private javax.swing.JTextField txt_mothername;
    // End of variables declaration//GEN-END:variables
}
