/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AidRequestRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.NgoEnterprise;
import Business.Network.Network;
import Business.Organization.AidRequestOrganization;
import Business.Organization.ApprovalOrganization;
import Business.Organization.Organization;
import Business.Organization.NgoManagerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkAidRequest;
import Business.WorkQueue.WorkRegistration;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class AidRequestWorkAreaPanel extends javax.swing.JPanel{

    
    private JPanel userProcessContainer;
    private AidRequestOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem ecosystem;
    private Network network;
    private int food=0;
    private Thread t;
    /**
     * Creates new form AidRequestWorkAreaPanel
     */
    public AidRequestWorkAreaPanel(JPanel userProcessContainer, UserAccount account, AidRequestOrganization organization, Enterprise enterprise,EcoSystem business,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.ecosystem=business;
        this.network=network;
        this.populatetable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        text_help = new javax.swing.JTextField();
        Button_sendrequest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        TextField_address = new javax.swing.JTextField();
        error_no = new javax.swing.JLabel();
        error_add = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel4.setText("Welcome To Aid Request Work Area ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel1.setText("Help For People  :");

        text_help.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        Button_sendrequest.setBackground(new java.awt.Color(51, 153, 255));
        Button_sendrequest.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_sendrequest.setText("Send Request");
        Button_sendrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_sendrequestActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sno", "Request", "Status", "ngo "
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel2.setText("Address:");

        TextField_address.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        error_no.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        error_no.setForeground(new java.awt.Color(255, 51, 51));

        error_add.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        error_add.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1)
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Button_sendrequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(text_help)
                            .addComponent(error_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(error_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextField_address, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(error_no, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error_add, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_help, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(Button_sendrequest, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
   
    
    public void populatetable()
    {
         DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        
        model.setRowCount(0);
        int x=0;
        
                    for (WorkAidRequest war : this.organization.getWorkQueue().getAidrequestList()){
                        if(war.getRequestsender()==this.userAccount)
                        {
                         Object[] row = new Object[4]; x++;
                         row[0] = x;
                         row[1] = war.getAmount();
                         row[2] = war;
                         row[3] = war.getNgoreciever();
                        
                         model.addRow(row);
                         }
                    }
       
    }
    
    
    public boolean validatef(){
        
        boolean bno=true , badd=true;
        String regex="\\d+";
        
         try
                {
                    error_no.setText("");
                Integer.parseInt(this.text_help.getText());
                }
                catch(NumberFormatException e)
                {
                if(text_help.getText().isEmpty()) this.error_no.setText("can not be empty");   
                else
                error_no.setText("enter valid number");
                bno=false;
                }
        
        if(this.TextField_address.getText().isEmpty())
        {
            this.error_add.setText("Plz Enter Text"); badd=false;
        }
        else if(TextField_address.getText().matches(regex))
                {
                    error_add.setText("can't be a number"); badd=false;
                }
        else this.error_add.setText("");
        
        if(!badd || !bno) return false;
        return true;
    }
    
    private void Button_sendrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_sendrequestActionPerformed
        // TODO add your handling code here:
        if(this.validatef()==false) return ;
        Organization org = null;
        Enterprise epp=null;
                WorkAidRequest war = new WorkAidRequest();
                war.setAmount(Integer.parseInt(this.text_help.getText()));
                war.setRequestsender(userAccount);
                war.setStatus("sent to Ngos");
                war.setAddress(this.TextField_address.getText());
                
                
                for (Enterprise enterprise : this.network.getEnterpriseDirectory().getEnterpriseList())
                {
                if (enterprise instanceof NgoEnterprise)
                   {
                       epp=enterprise;
                       System.out.println(enterprise);
                       for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
                       {
                       if (organization instanceof NgoManagerOrganization)
                          {
                              System.out.println(organization);
                            org = organization;
                            org.getWorkQueue().getAidrequestList().add(war);
                
                          }   
                       }
                
                
                   }   
                }
                if(epp==null)
                   {JOptionPane.showMessageDialog(null,"There is no Ngo Enterprise"); return;}
                
               if(org==null)
                   {JOptionPane.showMessageDialog(null,"There is no ngomanager Organization"); return;}
               
               this.organization.getWorkQueue().getAidrequestList().add(war);
               
               JOptionPane.showMessageDialog(null,"Request sent"); 
               this.populatetable();
        
    }//GEN-LAST:event_Button_sendrequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_sendrequest;
    private javax.swing.JTextField TextField_address;
    private javax.swing.JLabel error_add;
    private javax.swing.JLabel error_no;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField text_help;
    // End of variables declaration//GEN-END:variables
}
