/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CheckingRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ManagerOrganization;
import Business.Organization.CheckingOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRegistration;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import userinterface.ManagerRole.RefugeeDetailPanel;

/**
 *
 * @author hp
 */
public class CheckingAreaWorkJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private CheckingOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem ecosystem;
    private Network network;
    /**
     * Creates new form CheckingAreaWorkJPanel
     */
    public CheckingAreaWorkJPanel(JPanel userProcessContainer, UserAccount account, CheckingOrganization organization, Enterprise enterprise,EcoSystem business,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.ecosystem=business;
        this.network=network;
        populateRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button_checking = new javax.swing.JButton();
        Send = new javax.swing.JButton();
        Button_Assignme = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Button_seedetail = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        Button_checking.setBackground(new java.awt.Color(51, 153, 255));
        Button_checking.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_checking.setText("Checking");
        Button_checking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_checkingActionPerformed(evt);
            }
        });

        Send.setBackground(new java.awt.Color(51, 153, 255));
        Send.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Send.setText("Done");
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });

        Button_Assignme.setBackground(new java.awt.Color(51, 153, 255));
        Button_Assignme.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_Assignme.setText("Assign To Me ");
        Button_Assignme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_AssignmeActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sno", "RefugeeId", "Migrationcountry", "status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Button_seedetail.setBackground(new java.awt.Color(51, 153, 255));
        Button_seedetail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Button_seedetail.setText("See Details");
        Button_seedetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_seedetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Button_Assignme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_seedetail)
                        .addGap(159, 159, 159)
                        .addComponent(Button_checking)
                        .addGap(192, 192, 192)
                        .addComponent(Send, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Assignme)
                    .addComponent(Button_seedetail)
                    .addComponent(Button_checking)
                    .addComponent(Send))
                .addGap(143, 143, 143))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel4.setText("Welcome To Checking Work Area ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void populateRequestTable(){
        
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        
        model.setRowCount(0);
        int x=0;
        
        for (WorkRegistration register : this.organization.getWorkQueue().getRegistrationList()){
            if(register.getEmbassychecker()==null || register.getEmbassychecker()==this.userAccount)
                        {
                         Object[] row = new Object[4]; x++;
                         row[0] = x;
                         row[1]= register;
                         row[2] =register.getCountry();
                         row[3] = register.getStatus();
                         
                         model.addRow(row);
                         }
        }
                 

        
    }
    
    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        // TODO add your handling code here:

        int sr = jTable1.getSelectedRow();
        if(sr>=0)
        {

            WorkRegistration  wr =  (WorkRegistration) jTable1.getValueAt(sr, 1);
            if(wr.getEmbassychecker()==null)
             {
                 JOptionPane.showMessageDialog(null,"job Didnt assigned yet"); return;
             }
            if(!wr.getStatus().equals("checking in progress")){ JOptionPane.showMessageDialog(null,"Already done or checking not started"); return;}
            wr.setStatus("checking done");
            JOptionPane.showMessageDialog(null,"checking done ");
            this.populateRequestTable();
        }else
        {
            JOptionPane.showMessageDialog(null,"Please Select a specific detail ");
        }
    }//GEN-LAST:event_SendActionPerformed

    private void Button_checkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_checkingActionPerformed
        // TODO add your handling code here:
        
        

        int sr = jTable1.getSelectedRow();
        if(sr>=0)
        {

            WorkRegistration  wr =  (WorkRegistration) jTable1.getValueAt(sr, 1);
            if(wr.getEmbassychecker()==null)
             {
                 JOptionPane.showMessageDialog(null,"job Didnt assigned yet"); return;
             }
            if(!wr.getStatus().equals("Checker Recieved")){ JOptionPane.showMessageDialog(null,"Already checked"); return;}
            wr.setStatus("checking in progress");
            JOptionPane.showMessageDialog(null,"checking ");
            this.populateRequestTable();
            wr.setEmbassychecker(this.userAccount);
            
        }else
        {
            JOptionPane.showMessageDialog(null,"Please Select a specific detail ");
        }
    }//GEN-LAST:event_Button_checkingActionPerformed

    private void Button_AssignmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_AssignmeActionPerformed
        // TODO add your handling code here:

        int sr = jTable1.getSelectedRow();
        if(sr>=0)
        {
            WorkRegistration  wr =  (WorkRegistration) jTable1.getValueAt(sr, 1);
            if(!wr.getStatus().equals("sent to checking")){ JOptionPane.showMessageDialog(null,"Already Assigned"); return;}
            wr.setStatus("Checker Recieved");
            wr.setEmbassychecker(this.userAccount);
            JOptionPane.showMessageDialog(null,"job assigned");
            this.populateRequestTable();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Select a specific detail ");
        }
    }//GEN-LAST:event_Button_AssignmeActionPerformed

    private void Button_seedetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_seedetailActionPerformed
        // TODO add your handling code here:
        
        int sr = jTable1.getSelectedRow();
        if(sr>=0)
        {
            WorkRegistration  wr =  (WorkRegistration) jTable1.getValueAt(sr, 1);
            RefugeeDetailPanel refufeedetail = new RefugeeDetailPanel(userProcessContainer, userAccount, enterprise, network, wr);
            userProcessContainer.add("refufeedetail", refufeedetail);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Select a specific detail ");
        }
    }//GEN-LAST:event_Button_seedetailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Assignme;
    private javax.swing.JButton Button_checking;
    private javax.swing.JButton Button_seedetail;
    private javax.swing.JButton Send;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
